# Parameters for open_loop_intersection_node
# #Turn right through intersection
turn_left: #time, velocity, angular vel
  - [0.1, 0.0, 0.0]
  - [0.5, 0.43, 0]
  - [0.6, 0.43, 1.5]
  - [0.4, 0.43, 0.0]
turn_right:
  - [0.1, 0.0, 0.0]
  - [0.5, 0.43, 0]
  - [0.25, 0.35, -4.006]
  - [0.2, 0.43, 0.0]
turn_forward:
  - [0.1, 0.0, 0.0]
  - [0.5, 0.43, 0.0]
  - [0.7, 0.43, 0.0]
  - [0.4, 0.43, 0.0]
# turn_stop:
#   - [0.2, 0.0, 0.0]

#do we want to update the values based on where/what angle we stop at.
trajectory_reparam: 1
