tingbot:
  # Publish all joint states -----------------------------------
  /tingbot/joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  

  # Effort Controllers ---------------------------------------
  /tingbot/leftWheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: left_wheel_hinge
    pid: {p: 1.0, i: 0.0, d: 0.0}

  /tingbot/rightWheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: right_wheel_hinge
    pid: {p: 1.0, i: 0.0, d: 0.0}
