<?xml version="1.0"?>
<robot name="macros" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="pi" value="3.14159265359" />
    <xacro:property name="tile_thickness" value="0.01" />
	<physics type='ode'>
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1</real_time_factor>
      <real_time_update_rate>1000</real_time_update_rate>
      <gravity>0 0 -9.8</gravity>
    </physics>
    <!-- Defines a tile link and joint-->
    <xacro:macro name="tile" params="x y type:=empty rotation:=0 visible:=true">
        <link name="tile_${x}_${y}">
            <xacro:if value="${visible}" >
                <visual>
                    <origin xyz="${tile_width/2} ${tile_width/2} ${-tile_thickness/2}" rpy="0 0 ${rotation * pi/180}"/>
                    <geometry>
                        <mesh filename="package://rc_car_description/urdf/meshes/${type}.dae" />
                    </geometry>
                </visual>
		<inertial> 
    			<origin xyz="${tile_width/2} ${tile_width/2} ${-tile_thickness/2}" rpy="0 0 0"/> 
    			<mass value="100"/> 
     			<inertia  ixx="0" ixy = "0" ixz = "0"
    			iyy="0" iyz = "0"
    			izz="0"/>
  		</inertial>
	    <collision> 
    		<origin xyz="${tile_width/2} ${tile_width/2} ${-tile_thickness/2}" rpy="0 0 0"/> 
    		<geometry> 
      			 <box size="${tile_width} ${tile_width} ${tile_thickness}"/>
    		</geometry> 
		<surface>
            <friction>
              <ode>
                <mu>100</mu>
                <mu2>50</mu2>
              </ode>
            </friction>
            <bounce/>
            <contact>
              <ode/>
            </contact>
          </surface>
          <max_contacts>10</max_contacts>
  		</collision>
            </xacro:if>

        </link>

	<gazebo>
    <static>true</static>
	</gazebo>



        <joint name="world_to_tile_${x}_${y}" type="fixed">
            <parent link="world" />
            <child link="tile_${x}_${y}" />
            <origin xyz="${tile_width * x} ${tile_width * y} 0" />
        </joint>
    </xacro:macro>

<!-- *************************************************************-->


    <!-- Defines an april tag link and joint-->
    <xacro:macro name="tag" params="id x y pos rotation">
        <link name="tag_${id}">
            <visual>
                <origin xyz="-0.0254 -0.0254 0" />
                <geometry>
                    <mesh filename="package://rc_car_description/urdf/meshes/tags/tag_${id}.dae" />
                </geometry>
            </visual>
<collision> 
    		<origin xyz="0.025 0.025 0.025" rpy="0 0 0"/> 
    		<geometry> 
      			 <box size="0.025 0.025 0.025"/>
    		</geometry> 
		<surface>
            <friction>
              <ode>
                <mu>100</mu>
                <mu2>50</mu2>
              </ode>
            </friction>
            <bounce/>
            <contact>
              <ode/>
            </contact>
          </surface>
          <max_contacts>10</max_contacts>
  		</collision>
        </link>

        <joint name="world_to_tag_${id}" type="fixed">
            <parent link="tile_${x}_${y}" />
            <child link="tag_${id}" />
            <origin xyz="${pos} 0" rpy="0 0 ${rotation * pi/180}"/>
        </joint>
    </xacro:macro>
</robot>

